// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription

let version = "1.0.5"
let packageLibraryName = "Color"

// Products define the executables and libraries a package produces, making them visible to other packages.
var products = [
	Product.library(
        name: "\(packageLibraryName) Library", // has to be named different from the iOSApplication or Swift Playgrounds won't open correctly
        targets: [packageLibraryName]
    ),
]

// Targets are the basic building blocks of a package, defining a module or a test suite.
// Targets can depend on other targets in this package and products from dependencies.
var targets = [
	Target.target(
		name: packageLibraryName,
		dependencies: [
            .product(name: "Compatibility Library", package: "compatibility"), // apparently needs to be lowercase.  Also note this is "Device Library" not "Device"
		],
		path: "Sources"
	),
]

var platforms: [SupportedPlatform] = [
    .macOS("12"), // 10.15 minimum for SwiftUI on macOS, macOS 11 required for cgColor support, macOS 12 minimum for .brown, .cyan, .indigo, .mint, and .teal.
    .tvOS("15"), // 13 minimum for SwiftUI, 17 minimum for Menu
    .watchOS("8"), // 6 minimum for SwiftUI, watchOS 8 minimum for .brown, .cyan, .indigo, .mint, and .teal.

]

#if canImport(PlaygroundSupport)
platforms += [
    .iOS("15.2"), // minimum for Swift Playgrounds support
]
#else
platforms += [
    .iOS("15"), // 13 minimum for Combine/SwiftUI
]
#endif

#if os(visionOS)
platforms += [
    .visionOS("1.0"), // unavailable in Swift Playgrounds
]
#endif

#if canImport(AppleProductTypes) // swift package dump-package fails because of this
import AppleProductTypes

products += [
	.iOSApplication(
		name: packageLibraryName, // needs to match package name to open properly in Swift Playgrounds
		targets: ["\(packageLibraryName)TestAppModule"],
		teamIdentifier: "3QPV894C33",
		displayVersion: version,
		bundleVersion: "1",
		appIcon: .asset("AppIcon"),
		accentColor: .presetColor(.green),
		supportedDeviceFamilies: [
			.pad,
			.phone
		],
		supportedInterfaceOrientations: [
			.portrait,
			.landscapeRight,
			.landscapeLeft,
			.portraitUpsideDown(.when(deviceFamilies: [.pad]))
		],
		appCategory: .developerTools
	),
]

targets += [
	.executableTarget(
		name: "\(packageLibraryName)TestAppModule",
		dependencies: [
			.init(stringLiteral: packageLibraryName), // have to use init since normally would be assignable by string literal
		],
		path: "Development",
		resources: [
			.process("Resources")
		]
	),
//	.testTarget(
//		name: "\(packageLibraryName)Tests",
//		dependencies: [
//			.init(stringLiteral: packageLibraryName), // have to use init since normally would be assignable by string literal
//		],
//		path: "Tests"
//	),
]

#endif // for Swift Package compiling for https://swiftpackageindex.com/add-a-package

let package = Package(
    name: packageLibraryName,
    platforms: platforms,
    products: products,
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/kudit/Compatibility", "1.0.17"..<"2.0.0")
    ],
    targets: targets
)
